# Generated by Django 5.2.3 on 2025-07-04 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_chatmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TradeSimulation',
        ),
    ]
